"""Framework-neutral contracts: everything the platform's packages exchange (harness,
surfaces, Memory Service, A2A, schedulers). ADR 0001 in docs/adr describes the v2 seams."""

from importlib.metadata import version as _version

from trellis.contracts.a2a import (
    A2A_PROTOCOL_VERSION,
    AgentCapabilities,
    AgentCard,
    AgentInterface,
    AgentProvider,
    AgentSkill,
)
from trellis.contracts.artifacts import (
    OBSERVATION_KINDS,
    AgentWarning,
    ArtifactRef,
    Claim,
    EvidenceRef,
    MemoryObservation,
    RecommendedAction,
)
from trellis.contracts.context import AgentExecutionContext
from trellis.contracts.descriptors import AgentDescriptor, SkillDescriptor
from trellis.contracts.errors import (
    AgentCancelledError,
    AgentError,
    AgentPaused,
    AgentTimeoutError,
    ConfigurationError,
    ErrorCategory,
    HarnessError,
    MemoryUnavailableError,
    ModelError,
    PolicyDeniedError,
    ResultValidationError,
    ToolError,
    ToolNotFoundError,
    classify,
)
from trellis.contracts.evaluation import JudgeMethod, JudgeVerdict
from trellis.contracts.events import AgentEvalEvent, LifecycleEvent
from trellis.contracts.feedback import Feedback, FeedbackSource, FeedbackTargetKind, FeedbackVerdict
from trellis.contracts.ids import new_id, now, safe_id, stable_id
from trellis.contracts.messages import AgentRequest, AgentResponse, AgentStatus
from trellis.contracts.model import ModelRequest, ModelResponse, ModelUsage
from trellis.contracts.ports import (
    AgentDirectory,
    AgentInterceptor,
    AgentPolicyProvider,
    AgentRegistryClient,
    ArtifactClient,
    EvaluationProvider,
    EvaluationSink,
    EventSink,
    FeedbackStore,
    FrameworkAdapter,
    Judge,
    LifecycleListener,
    MemoryPort,
    ModelClient,
    PromptProvider,
    RunStore,
    Scheduler,
    TelemetryProvider,
    TelemetryRedactor,
    ToolClient,
)
from trellis.contracts.runs import (
    Interrupt,
    InterruptDecision,
    InterruptReason,
    InterruptResolution,
    RunEvent,
    RunEventType,
    RunOutcome,
    RunRecord,
    RunStart,
    RunStatus,
    Schedule,
    ScheduleSpec,
)
from trellis.contracts.tool import ToolCall, ToolOutcome, ToolSpec, ToolStatus

__version__ = _version("trellis-contracts")

__all__ = [
    "A2A_PROTOCOL_VERSION",
    "OBSERVATION_KINDS",
    "AgentCancelledError",
    "AgentCapabilities",
    "AgentCard",
    "AgentDescriptor",
    "AgentDirectory",
    "AgentError",
    "AgentEvalEvent",
    "AgentExecutionContext",
    "AgentInterceptor",
    "AgentInterface",
    "AgentPaused",
    "AgentPolicyProvider",
    "AgentProvider",
    "AgentRegistryClient",
    "AgentRequest",
    "AgentResponse",
    "AgentSkill",
    "AgentStatus",
    "AgentTimeoutError",
    "AgentWarning",
    "ArtifactClient",
    "ArtifactRef",
    "Claim",
    "ConfigurationError",
    "ErrorCategory",
    "EvaluationProvider",
    "EvaluationSink",
    "EventSink",
    "EvidenceRef",
    "Feedback",
    "FeedbackSource",
    "FeedbackStore",
    "FeedbackTargetKind",
    "FeedbackVerdict",
    "FrameworkAdapter",
    "HarnessError",
    "Interrupt",
    "InterruptDecision",
    "InterruptReason",
    "InterruptResolution",
    "Judge",
    "JudgeMethod",
    "JudgeVerdict",
    "LifecycleEvent",
    "LifecycleListener",
    "MemoryObservation",
    "MemoryPort",
    "MemoryUnavailableError",
    "ModelClient",
    "ModelError",
    "ModelRequest",
    "ModelResponse",
    "ModelUsage",
    "PolicyDeniedError",
    "PromptProvider",
    "RecommendedAction",
    "ResultValidationError",
    "RunEvent",
    "RunEventType",
    "RunOutcome",
    "RunRecord",
    "RunStart",
    "RunStatus",
    "RunStore",
    "Schedule",
    "ScheduleSpec",
    "Scheduler",
    "SkillDescriptor",
    "TelemetryProvider",
    "TelemetryRedactor",
    "ToolCall",
    "ToolClient",
    "ToolError",
    "ToolNotFoundError",
    "ToolOutcome",
    "ToolSpec",
    "ToolStatus",
    "classify",
    "new_id",
    "now",
    "safe_id",
    "stable_id",
]
