"""Framework-neutral contracts: everything the platform's packages exchange (harness,
surfaces, Memory Service, A2A, agent-runs). ADRs 0001 and 0002 in docs/adr describe the
seams."""

from importlib.metadata import version as _version

from trellis.contracts.a2a import (
    A2A_PROTOCOL_VERSION,
    AgentCapabilities,
    AgentCard,
    AgentInterface,
    AgentProvider,
    AgentSkill,
)
from trellis.contracts.artifacts import (
    OBSERVATION_KINDS,
    AgentWarning,
    ArtifactRef,
    Claim,
    EvidenceRef,
    MemoryObservation,
    ObservationKind,
    RecommendedAction,
)
from trellis.contracts.context import AgentExecutionContext
from trellis.contracts.descriptors import AgentDescriptor, SkillDescriptor
from trellis.contracts.errors import (
    ERROR_SOURCES,
    AgentCancelledError,
    AgentError,
    AgentPaused,
    AgentTimeoutError,
    ConfigurationError,
    ErrorCategory,
    ErrorSource,
    HarnessError,
    MemoryUnavailableError,
    ModelError,
    PolicyDeniedError,
    ResultValidationError,
    ToolError,
    ToolNotFoundError,
    classify,
)
from trellis.contracts.evaluation import JudgeMethod, JudgeVerdict
from trellis.contracts.events import AgentEvalEvent
from trellis.contracts.feedback import Feedback, FeedbackSource, FeedbackTargetKind, FeedbackVerdict
from trellis.contracts.ids import new_id, now, safe_id, stable_id
from trellis.contracts.messages import AgentRequest, AgentResponse, AgentStatus
from trellis.contracts.model import ModelRequest, ModelResponse, ModelUsage
from trellis.contracts.ports import (
    AgentDirectory,
    AgentInterceptor,
    AgentPolicyProvider,
    ArtifactClient,
    EvaluationProvider,
    EventSink,
    Judge,
    MemoryPort,
    ModelClient,
    RunStore,
    TelemetryProvider,
    TelemetryRedactor,
    ToolClient,
)
from trellis.contracts.runs import (
    Interrupt,
    InterruptDecision,
    InterruptReason,
    InterruptResolution,
    InterruptUI,
    RunEvent,
    RunEventType,
    RunOutcome,
    RunRecord,
    RunStart,
    RunStatus,
    Schedule,
    ScheduleSpec,
)
from trellis.contracts.tool import ToolCall, ToolOutcome, ToolSource, ToolSpec, ToolStatus

__version__ = _version("trellis-contracts")

__all__ = [
    "A2A_PROTOCOL_VERSION",
    "ERROR_SOURCES",
    "OBSERVATION_KINDS",
    "AgentCancelledError",
    "AgentCapabilities",
    "AgentCard",
    "AgentDescriptor",
    "AgentDirectory",
    "AgentError",
    "AgentEvalEvent",
    "AgentExecutionContext",
    "AgentInterceptor",
    "AgentInterface",
    "AgentPaused",
    "AgentPolicyProvider",
    "AgentProvider",
    "AgentRequest",
    "AgentResponse",
    "AgentSkill",
    "AgentStatus",
    "AgentTimeoutError",
    "AgentWarning",
    "ArtifactClient",
    "ArtifactRef",
    "Claim",
    "ConfigurationError",
    "ErrorCategory",
    "ErrorSource",
    "EvaluationProvider",
    "EventSink",
    "EvidenceRef",
    "Feedback",
    "FeedbackSource",
    "FeedbackTargetKind",
    "FeedbackVerdict",
    "HarnessError",
    "Interrupt",
    "InterruptDecision",
    "InterruptReason",
    "InterruptResolution",
    "InterruptUI",
    "Judge",
    "JudgeMethod",
    "JudgeVerdict",
    "MemoryObservation",
    "MemoryPort",
    "MemoryUnavailableError",
    "ModelClient",
    "ModelError",
    "ModelRequest",
    "ModelResponse",
    "ModelUsage",
    "ObservationKind",
    "PolicyDeniedError",
    "RecommendedAction",
    "ResultValidationError",
    "RunEvent",
    "RunEventType",
    "RunOutcome",
    "RunRecord",
    "RunStart",
    "RunStatus",
    "RunStore",
    "Schedule",
    "ScheduleSpec",
    "SkillDescriptor",
    "TelemetryProvider",
    "TelemetryRedactor",
    "ToolCall",
    "ToolClient",
    "ToolError",
    "ToolNotFoundError",
    "ToolOutcome",
    "ToolSource",
    "ToolSpec",
    "ToolStatus",
    "classify",
    "new_id",
    "now",
    "safe_id",
    "stable_id",
]
